// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4R-tjeW61mIh5BPHwL5RJmh_ytqVnt7E',
    appId: '1:650127179574:web:b120c0b4ddabe820b7fd97',
    messagingSenderId: '650127179574',
    projectId: 'sloter',
    authDomain: 'sloter.firebaseapp.com',
    storageBucket: 'sloter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkWbCe617-h_8pIC0Q5qFfcmw2H9tH_B4',
    appId: '1:650127179574:android:6c9d54dfade64de7b7fd97',
    messagingSenderId: '650127179574',
    projectId: 'sloter',
    storageBucket: 'sloter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgn-rY5tA15kkazdrOXKphv-CB-1XMK9c',
    appId: '1:650127179574:ios:0ba31419431f58bbb7fd97',
    messagingSenderId: '650127179574',
    projectId: 'sloter',
    storageBucket: 'sloter.appspot.com',
    iosClientId: '650127179574-tkgol4sk8cpr17odaav2m15m32v5kk0l.apps.googleusercontent.com',
    iosBundleId: 'com.example.sloter',
  );
}
